### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by amanshah10** [dlbunker/ps-spring-boot-and-angular#2]
When I run 'node server.js', it shows me error that no such a file (index.html) or directory **'......../bike-ui/dist/index.html'**. Please help me to solve this problem. I have attached a screenshot of my error.
![screenshot 34](https://user-images.githubusercontent.com/19285024/47612715-1f56ab00-daa6-11e8-8390-38e47f54bea8.png)

**Comment by amanshah10** [comment]
I got it. Now, my app is running properly.

**Comment by bharathnatarajan1** [comment]
I am getting same error as shown below:
API running on 4200
Error: ENOENT: no such file or directory, stat 'C:\dev\projects\bike-ui\dist\index.html'

How to solve this??

**Comment by snlaccount** [comment]
update server.js to point to dist/<app name> and dist/<app name>/index.html path.

**Comment by k-romero** [comment]
When you say point to dist/ and dist//index.html path....what exactly do you mean? My index.html is def there. But its not finding it for some reason, and the path is accurate.
